[versions]
androidGradlePlugin = "9.0.0-alpha02"
appVersion = "0.1.6"

kotlin = "2.2.10"
kotlinCoroutines = "1.10.2"
kotlinxAtomicfu = "0.29.0"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.9.0"

androidBuildTools = "36.0.0"
androidSdk = "36"
androidSdkMinimum = "26"

kmpIo = "0.3.0"
kmpCrypto = "0.1.7"
kmpMarkup = "0.1.0"
bignum = "0.3.10"
bouncycastle = "1.81"

dokkaPlugin = "2.0.0"
vannikTech = "0.34.0"

junit = "4.13.2"
junit5Version = "5.13.4"
androidxTest = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTestExt = "1.3.0"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization"}

kmp-io = { module = "io.github.skolson:kmp-io", version.ref = "kmpIo" }
kmp-markup = { module = "io.github.skolson:kmp-markup", version.ref = "kmpMarkup" }
kmp-crypto = { module = "io.github.skolson:kmp-crypto", version.ref = "kmpCrypto" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle"}

#build only
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5Version" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5Version" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest"}
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref="androidxTestExt" }

[bundles]
androidx-test = [ "androidx-test-core", "androidx-test-runner", "androidx-test-ext"]

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish-vannik = { id = "com.vanniktech.maven.publish", version.ref = "vannikTech" }

dokka-base = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }